
- name: configure /etc/hosts on the host
  template: src=hosts.j2 dest=/etc/hosts

- name: configure lo:0
  template: src=loopback.j2 dest=/etc/sysconfig/network-scripts/ifcfg-lo:0

- name: configure eth2
  template: src=uplink1.j2 dest=/etc/sysconfig/network-scripts/ifcfg-eth2

- name: configure eth3
  template: src=uplink2.j2 dest=/etc/sysconfig/network-scripts/ifcfg-eth3
